[book]
authors = ["Howard Hu"]
language = "en"
multilingual = false
src = "src"
title = "Design Patterns in Go"


[output.html]
mathjax-support = true
git-repository-url = "https://github.com/howdhu/design-patterns-go/tree/main"
edit-url-template = "https://github.com/howdhu/design-patterns-go/tree/main/{path}"